### ISSUE TITLE
New Feature Request: Download throttle - Pause between each request to website

### ISSUE THREAD

**Issue by Ferretaa** [BilderHerunterlader/BilderHerunterlader#4]
With reference to the discussion in the link below, is it possible to add the ability to have a pause introduced between requests to a site so as to slow down the number of requests that occur with a short period of time? 
Perhaps being able to delay between each request up to XX seconds or a minimum of XX seconds to a maximum  of XX seconds randomly chosen?

With the discussion going on here: 
[ImageFap.com • View topic - Too many requests. Retry in 1 hour?: https://www.imagefap.com/forum/viewtopic.php?f=4&t=17675](https://www.imagefap.com/forum/viewtopic.php?f=4&t=17675)

**Comment by BilderHerunterlader** [comment]
What? Only 100 Requests per minute? This is crazy. I can easily browse that fast with a Mouse...

It is already possible to define a wait time in the rule definition, even for different parser steps per rule.

100 requests per 1 min
200 requests per 5 min
1000 requests per 1 hour

60s -> 100
1s -> 1.6666666666666666666666666666667

200s -> 300s
1s -> 1.5

1000s -> 3600s
1s -> 3.6

So I'd would have to define a wait time, so that 1.5 requests per second are not exceeded based on those limits.
And if they count requests to the image also (which they probably do), then I need to cut that in half again to 0.75 requests per second.
But then you still need some requests to browse the galleries with the browser. OK, this is kind of avoidable by browser all galeries first and then wait some time and start downloads with BH.

0.75 requests -> 1000ms
1333.3333333333333333333333333333
So if I have not miscalculated something a wait time of 1334 is necessary.

If you would like to test this, you could edit the rule with the rule editor, and define that wait time on the first (and only) Regex Pipeline.

**Comment by Ferretaa** [comment]
Ok, I'll give it a shot and let you know
:)

**Comment by Ferretaa** [comment]
Ok that works - thanks for your help :)
